[project]
name = "tool-zipping"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Alin Opris", email = "alin.opris@protonmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pytest", 
]

[project.scripts]
tool-zipping = "tool_zipping:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"

